next.config.js
Loading a nested route (ex: `/dashboard`) leads to the following view:
Tweaking the default nextjs config to not output plain directories without an index.html to avoid directory indexation in IPFS.
```
├── dashboard
│   ├── function
│   │   └── index.html
│   ├── index.html
│   ├── manage
│   │   └── index.html
│   └── volume
│       └── index.html
```
```
├── dashboard
│   ├── function.html
│   ├── manage.html
│   └── volume.html
```
=> Fix "empty directory listing" bug

.github/workflows/build_check.yaml, src/components/common/FeatureCard/types.ts, src/components/pages/dashboard/index/AllTabContent/cmp.tsx, src/components/pages/dashboard/index/VolumesTabContent/cmp.tsx, src/components/pages/dashboard/manage/ManageFunction/cmp.tsx, src/components/pages/dashboard/manage/ManageVolume/cmp.tsx, src/components/pages/dashboard/manage/VolumeList/cmp.tsx, src/domain/volume.ts, src/hooks/common/useForm.ts
Project could not be built: 
- Type error when calling the `humanReadableSize` with an invalid string (~~mb~~ -> MiB)
- Importing an undefined constant `pricePerMiB`
- Fixed default any on a recursive method (lack of explicit return type)
In order to prevent this from further happening, I added an action that builds the project when opening a PR.
=> Fix: Broken build

src/components/form/AddFunctionCode/cmp.tsx, src/domain/program.ts, src/helpers/schemas.ts, src/hooks/form/useAddFunctionCode.ts
Closes #43
- Entrypoint cas be selected under the `Upload code` section
- Entrypoint is not needed when using the online editor
- Entrypoint could be any string, but cannot be empty (mandatory field)
=> Feature: User can now chose an entrypoint for their program

package-lock.json
Those subdependencies used unsafe regex results.
- bumped `semver`
- bumped `word-wrap`
*Automatically fixed using `npm audit fix`
=> Fix security warning in dependencies (unsafe regex)

src/components/pages/dashboard/NewVolumePage/cmp.tsx, src/helpers/schemas.ts
`.squashfs` is a common file suffix for squashFS files, just like `.sqsh`.
Also, fixed a typo where it looked like you were uploading a function, not a volume.
=> Allow .squasfs file suffix in volume upload

src/components/common/StatusLabel/cmp.tsx, src/components/common/StatusLabel/types.ts, src/components/pages/dashboard/manage/ManageDomain/cmp.tsx, src/components/pages/dashboard/manage/ManageFunction/cmp.tsx, src/components/pages/dashboard/manage/ManageInstance/cmp.tsx, src/components/pages/dashboard/manage/ManageSSHKey/cmp.tsx, src/components/pages/dashboard/manage/ManageVolume/cmp.tsx, src/domain/domain.ts, src/hooks/pages/dashboard/manage/useManageDomain.ts
This feature allow users to revalidate their custom domain if the DNS check has failed. It works by sending a new aggregate message with a timestamp (to force an update).
=> Add a retry mechanism for custom domains

src/components/common/Header/cmp.tsx, src/hooks/pages/useHeader.ts
**Issue:**
The wallet picker for connecting/disconnecting a wallet was not displaying on mobile devices.
**Changes Made:**
I have addressed the issue by adding the following code to the `mobileTopContent` section of the `StyledNavbar` component:
```jsx
<div tw="absolute right-0 mt-10" ref={divRefMobile}>
{displayWalletPicker && WalletPickerComponent()}
</div>
```
Additionally, a new divRefMobile has been added for mobile devices.
**Test Plan:**
I have tested the changes on various mobile devices and verified that the wallet picker now displays correctly. I have also ensured that users can connect and disconnect their wallets as expected.
**Screenshots**
**Checklist**
I have tested these changes thoroughly.
All existing tests pass.
I have updated the documentation, if necessary.
=> FIXED: Logout doesn't work on mobile

src/domain/program.ts
While Aleph-vm technically support plain encoding for program source, it does not seem to work as is.
As a temporary fix, send the program source as a zipped file
This fixes a regression that was potentially introduced in #56
=> Aleph-VM does not support plain encoding for PROGRAM src

src/hooks/common/useConnect.ts, src/hooks/pages/useHeader.ts
The issue was related to how the connect function handled error cases. Previously, all errors were assumed to be network switching cases, but the caught error was actually due to multiple calls to this function (not yet resolved, with the specific error 'wallet_addEthereumChain already pending'). For now, this error is being bypassed.
Changes:
Moved the network switching functionality into a specific function, rather than handling it in the connect function's catch block.
Related:
It's unclear to me how the WalletPicker component shares the state of the selected network with the app. It seems that this state is isolated. [WalletPicker Component](https://github.com/aleph-im/front-core/blob/main/src/components/modules/WalletPicker/cmp.tsx)
The handleConnect function is called without a …
=> Fix: Switching network inconsistencies

src/hooks/common/useConnect.ts
I noticed that in the connection function Promise.all was used, to maybe in the future allow multiple wallet connections in the app, so multiple balances to fetch
=> fix: update balances when switching networks

.env
Solution: Disable the NextJS telemetry by default using an environment variable.
=> Fix: `npm dev` exfiltrated private data to NextJS telemetry

src/components/form/AddFunctionCode/cmp.tsx
The **More Info** tooltip has been replaced by the **Learn More** button, which redirects to the docs dedicated to uploading/write your code.
=> Replace Tooltip with a link Learn More

README.md
Problem: Running `npm i` on a fresh repository fails due to a missing authentication token for the proprietary Font Awesome icon font.
This documents that fact instead of solving the core issue.
=> Fix: README.md did not explain fontawesome auth

src/components/pages/dashboard/ManageDomain/cmp.tsx, src/components/pages/settings/NewDomainPage/cmp.tsx, src/domain/confidential.ts, src/domain/domain.ts, src/helpers/constants.ts, src/helpers/schemas/base.ts, src/helpers/utils.ts, src/hooks/common/useManager/useEntityManager.ts, src/hooks/pages/settings/useNewDomainPage.ts, src/hooks/pages/solutions/manage/useManageDomain.ts, src/store/entity.ts
This is a draft, I just wanted to test some stuff and I ended up doing few fixes/improvements:
- Continued confidential current implementation (needed for the following changes)
- Fixed /settings/domain/[domain] for cocos
- Updated /settings/domain/new to add coco support
- Display the right entity type for cocos
=> Add domain support for confidentials

src/domain/executable.ts, src/hooks/common/useEntityCost.ts
https://aleph-im.atlassian.net/browse/ALEPH-293
As we released the confidential VMs we need to put the half pricing on normal instances and half of the flow price also, but remain confidentials as it is.
On the Console page we replicate the same cost logic than in pyaleph, so we also need to modify it as we are calculating the price before sending the message.
=> feat: Reduce persistent entities pricing

src/components/form/SelectInstanceSpecs/cmp.tsx, src/domain/executable.ts, src/domain/gpuInstance.ts, src/domain/program.ts, src/hooks/pages/computing/useNewGpuInstancePage.ts
When creating a new GPU instance it was setting by default the hardcoded tier and it was allowing the user to create gpu with lower resources.
Fixed by setting the default specs empty instead.
=> fix: wrong gpu default specs

src/hooks/common/useEntityCost.ts
- Add debounce mechanism to `/estimate` endpoint calls in the cost calculation hook
- Reduces API call frequency when form values change rapidly
- Implements a 300ms delay before triggering cost recalculation
- Optimizes component rendering with useMemo
- Open any entity creation form (instance, GPU instance, etc.)
- Quickly change multiple form values
- Verify in the network tab that fewer `/estimate` API calls are made
=> Fix: Add debounce to cost calculation API calls

src/helpers/schemas/base.ts, src/helpers/schemas/execution.ts
This PR adds validation to the volume name field in the volume creation form to only allow alphanumeric characters, underscores, and dashes.
- Created a new schema `requiredVolumeNameSchema` in base.ts with a specific error message
- Updated the `persistentVolumeSchema` in execution.ts to use the new validation
- Added regex pattern `/^[a-zA-Z0-9_-]+$/` for validation
- Added a descriptive error message: "Volume name can only contain letters, numbers, underscores, and dashes"
- Try to create a new persistent volume with:
- Valid name (e.g. "my-volume_123"): should work
- Name with special characters (e.g. "test!volume"): should show validation error
- Name with spaces (e.g. "test volume"): should show validation error
=> Fix: Add volume name validation to allow only alphanumeric, underscore, and dash characters

src/helpers/schemas/base.ts
- Updates the Linux path validation schema to restrict mount paths to only contain alphanumeric characters, underscores, and dashes
- Maintains the existing path structure validation (must start with / and have proper format)
- Provides a clear error message when invalid characters are used
- Try to create a volume with mount path containing invalid characters (like spaces, special characters)
- Verify valid mount paths (with alphanumeric, underscores, dashes) work correctly
- Test paths with multiple segments (e.g., /data/files)
=> Fix: Restrict mount path validation to alphanumeric, underscores, and dashes

src/components/common/ButtonWithInfoTooltip/cmp.tsx, src/components/common/ButtonWithInfoTooltip/index.ts, src/components/common/ButtonWithInfoTooltip/styles.tsx, src/components/pages/computing/NewGpuInstancePage/cmp.tsx, src/components/pages/computing/NewInstancePage/cmp.tsx
This PR adds a feature that displays an info icon in disabled buttons when there's a tooltip explaining why the button is disabled.
- Created a new `ButtonWithInfoTooltip` component that automatically shows an info icon when a button is disabled and has tooltip content
- Implemented the new component in checkout buttons and "manually select CRN/GPU" buttons in instance creation forms
- Ensures that tooltips are properly positioned and only shown when a button is disabled and has explanation content
- Removed redundant tooltip code and cleaned up imports
To test this feature:
1. Navigate to the Instance creation or GPU Instance creation pages
2. Check for cases where buttons are disabled (e.g., "Manually select CRN" when not appropriate)
3. Verify that an info icon appears on the disabled …
=> Feat: Add info icons to disabled buttons with tooltips

src/components/form/CheckoutSummary/cmp.tsx, src/domain/executable.ts, src/helpers/schemas/instance.ts, src/helpers/utils.ts
- Added rootfs size to ExecutableCostProps to use actual system volume size in cost
calculations
- Modified cost calculation to include the rootfs volume cost in execution cost
- Added support for volume discount display in costs breakdown
- Fixed displaying of negative costs for volume discounts
- Added validation for system volume size against SDK maximum
- Create an instance with a custom system volume size
- Verify that the cost calculation correctly includes the system volume price
- Verify that any applicable volume discounts are displayed in the cost breakdown with
negative values
- Verify that the total cost is calculated correctly when discounts are applied
=> Fix: correctly account for system volume price in cost calculation

src/hooks/pages/computing/useNewInstancePage.ts
- Fixes a usability issue that prevented users from switching payment methods in certain situations:
- When not connected to a wallet
- When connected to an incompatible network
- Users can now freely switch between PAYG (Pay-as-you-go) and Holding tier payment methods in all circumstances
- The submit button will still be disabled with appropriate error messages when the selected payment method is incompatible
- This change only affects regular instances, as GPU instances are restricted to PAYG payment method only
- Simplified the code by removing unnecessary conditional logic and useMemo hooks
1. Open the "Create new instance" page without connecting a wallet
2. Verify that the payment method toggle works and can be switched between Holding tier and PAYG
3. Connect to an incompatible …
=> Fix: Allow payment method switching regardless of connection state or network

src/helpers/schemas/base.ts
- Fixed domain name validation regex to allow multiple levels of subdomains (e.g., sub1.sub2.example.com)
- Previously the validation only allowed one level of subdomain
- Updated regex pattern by adding the '+' quantifier to the subdomain part
- Manually verify that domains with multiple levels like sub1.sub2.example.com can now be used
- Ensure existing single-level subdomains continue to work
=> Fix domain validation to support multi-level subdomains

src/store/connection.ts
- Fixes an issue where the payment method selection was reset when disconnecting a wallet
- Now preserves the user's payment method choice after wallet disconnection
- Connect wallet and select PAYG payment method
- Disconnect wallet
- Verify payment method remains set to PAYG instead of resetting to HOLD
=> Fix: Preserve payment method when disconnecting wallet

src/helpers/errors.ts, src/hooks/common/useExecutableActions.ts
- Fixes bug where PAYG instances could be incorrectly deleted when user is on the wrong network (eg. Ethereum instead of Base/Avax)
- Now shows a clear error message requiring the user to manually switch to the correct network before deletion
- Prevents deletion of payment streams without proper network context
- Refactors network checking into a reusable function
1. Create a PAYG instance on Base or Avalanche
2. Switch to Ethereum network
3. Try to delete the instance
4. Verify that proper error message is shown (should indicate which network to use)
5. Switch to the correct network and verify deletion works properly
=> fix: ensure correct network for deleting PAYG instances

src/components/common/Content/cmp.tsx, src/components/common/Content/index.ts, src/components/common/Content/styles.tsx, src/hooks/common/useResetScroll.ts, src/pages/_app.tsx, src/styles/global.tsx
- Implemented automatic scroll reset when navigating between pages for a smoother user experience
- Created a reusable useResetScroll hook for consistent scroll behavior across the application
- Added smooth scrolling animation to make page transitions feel more polished
This PR addresses the issue where scroll position was retained when navigating between pages, causing users to start new pages at the same scroll position they left the previous page.
- Created a custom useResetScroll hook that handles scroll position reset for both window and specific container elements
- Implemented the hook in the main App component and Content component
- Used the ScrollBehavior API to enable smooth scrolling transitions
- Verified scroll reset works when navigating between pages with different scroll …
=> fix: scroll to top when navigating

src/components/pages/console/confidential/ConfidentialDashboardPage/cmp.tsx
The button for GPU instances has a "Create a GPU Instance" label while the button for confidential VMs reads "Create Confidential". Harmonized the two.
=> fix: use same wording for button labels to create instances
